-- jdbc:oracle:thin:@10.54.5.68:1521:dsp
-- jdbc:oracle:thin:@10.11.10.12:1521:app
ALTER TABLE DSP_COMPANY ADD DEBT_AMOUNT NUMBER(15);
/
-- note: update Database: DC_OWNER bang DSP_COMPANY tuong tu.

ALTER TABLE DSP_COMP_VAS_MOBILE ADD (NAME VARCHAR(100), ADDRESS VARCHAR(100));
/

CREATE TABLE DSP_COMP_DEBT
(
    ID NUMBER(15)  not null
        constraint PK_DSP_COMP_DEBT
            primary key,
    COM_ID     NUMBER(15)   not null
        constraint FK_DSP_COMP_DEBT
            references DSP_COMPANY,
    TYPE VARCHAR2(1) not null,
    CREATE_TIME DATE not null,
    TOTAL_AMOUNT NUMBER(15) not null,
    PAID_AMOUNT NUMBER(15),
    CONFIRM_TIME DATE,
    STATUS VARCHAR2(2) not null,
    DESCRIPTION VARCHAR2(4000),
    ORDER_ID NUMBER(15)
);
/

create table DIG_SUB_SERVICE
(
    ISDN           VARCHAR2(20)          not null,
    TYPE           VARCHAR2(50)          not null,
    PACKAGE_CODE   VARCHAR2(50)          not null,
    START_TIME     DATE                  not null,
    END_TIME       DATE,
    INITIAL_AMOUNT NUMBER(10),
    PROFILE        VARCHAR2(30),
    SERIAL         VARCHAR2(30)
)
/

CREATE SEQUENCE DSP_COMP_DEBT_SEQ
    START WITH     1
    INCREMENT BY   1
    NOCACHE
    NOCYCLE;
commit;

INSERT INTO AP_PARAM(PAR_TYPE, PAR_NAME, PAR_VALUE, DESCRIPTION) VALUES ('SRV_CODE', 'DataCode', '43', 'Dịch vụ Datacode');
INSERT INTO AP_PARAM(PAR_TYPE, PAR_NAME, PAR_VALUE, DESCRIPTION) VALUES ('SRV_CODE', 'MobiEdu', '80', 'Dịch vụ MobiEdu');
INSERT INTO AP_PARAM(PAR_TYPE, PAR_NAME, PAR_VALUE, DESCRIPTION) VALUES ('SRV_CODE', 'MobiOn', '91', 'Dịch vụ MobiOn');
INSERT INTO AP_PARAM(PAR_TYPE, PAR_NAME, PAR_VALUE, DESCRIPTION) VALUES ('SRV_CODE', 'ClipTV', '92', 'Dịch vụ ClipTV');

ALTER TABLE DSP_SERVICE_PRICE_TAB ADD TYPE NUMBER(2);
UPDATE DSP_SERVICE_PRICE_TAB SET TYPE = 0 WHERE DEF = 1;

INSERT INTO DSP_SERVICE (SERVICE_ID, SERVICE_NAME, STATUS, SERVICE_CODE, DESCRIPTION, PATH) VALUES (DSP_SERVICE_SEQ.nextval, 'MobiOn', '1', 'MO', 'mobiOn', 'mobiOn');
INSERT INTO DSP_SERVICE (SERVICE_ID, SERVICE_NAME, STATUS, SERVICE_CODE, DESCRIPTION, PATH) VALUES (DSP_SERVICE_SEQ.nextval, 'ClipTV', '1', 'CT', 'clipTv', 'clipTv');

ALTER TABLE DIP_SUB_SERVICE ADD ALERT_END_TIME VARCHAR2(1) default '0';

ALTER TABLE AM_USER ADD (TPS NUMBER(10), SEESION NUMBER(10));
/

create table DSP_COMPANY_HISTORY
(
    COM_ID        NUMBER(15)  not null
        constraint FK_DSP_COM_HIS_REF_DSP_COMPANY
            references DSP_COMPANY,
    OLD_PARENT      NUMBER(15) not null,
    NEW_PARENT      NUMBER(15) not null,
    USER_ID         NUMBER(10)  not null,
    ISSUE_TIME      DATE        not null
)
/

ALTER TABLE DIG_SUB_SERVICE ADD CHANNEL VARCHAR2(1);
COMMENT ON COLUMN DIG_SUB_SERVICE.CHANNEL IS '1:SMS, 2:WEB, 3:API';

ALTER TABLE DIP_SUB_SERVICE ADD REQUEST_ID VARCHAR2(50);
ALTER TABLE DIP_SUB_SERVICE_HIST ADD REQUEST_ID VARCHAR2(50);

ALTER TABLE DSP_SMS_COMMAND ADD SYS_TYPE VARCHAR2(1);
COMMENT ON COLUMN DSP_SMS_COMMAND.SYS_TYPE IS '0:KHDN, 1:KHCN';

ALTER TABLE DSP_LOYALTY_DTL ADD SMS_TYPE VARCHAR2(1);

INSERT INTO AP_PARAM (PAR_NAME, PAR_TYPE, PAR_VALUE, DESCRIPTION) VALUES ('LOYALTYDD', 'LOYALTY_COMPANY', '1181', 'Com_id và cmd sms doi diem');
INSERT INTO AP_PARAM (PAR_NAME, PAR_TYPE, PAR_VALUE, DESCRIPTION) VALUES ('LOYALTYSN', 'LOYALTY_COMPANY', '1101', 'sms sinh nhật');

