CREATE DATABASE LINK "db_90012"
    CONNECT TO "qlpn" IDENTIFIED BY "qlpn"
    USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 10.10.8.181)(PORT = 1521)))(CONNECT_DATA =(SID = tc8)(SERVER = SHARED)))';


GRANT CREATE ANY MATERIALIZED VIEW TO qlpn;